"use strict";
// ---------- Small hand-pixelled icons (HUD and pickups) ----------
// Letters map to [ramp, tone] so icons follow the active palette.
// Light always comes from the upper left: highlights top-left, darks bottom-right.

const ICON_DEFS = {
  heart: {
    legend: { k: "ink", w: ["white", 0], d: ["red", 3], c: ["red", 2], b: ["red", 1] },
    rows: [
      "..kkk....kkk..",
      ".kwddk..kccck.",
      "kwdddckkcccbbk",
      "kdddccccccccbk",
      "kddcccccccccbk",
      "kdccccccccccbk",
      ".kcccccccccbk.",
      "..kcccccccbk..",
      "...kcccccbk...",
      "....kcccbk....",
      ".....kcbk.....",
      "......kk......",
    ],
  },
  heartHalf: {
    legend: { k: "ink", w: ["white", 0], d: ["red", 3], c: ["red", 2], b: ["red", 1], e: ["neutral", 1], f: ["neutral", 0] },
    rows: [
      "..kkk....kkk..",
      ".kwddk..keeek.",
      "kwdddckkeeeffk",
      "kdddccceeeeefk",
      "kddccccfeeeefk",
      "kdcccccfeeeefk",
      ".kccccceeeefk.",
      "..kccccfeefk..",
      "...kcccfefk...",
      "....kccffk....",
      ".....kcfk.....",
      "......kk......",
    ],
  },
  heartEmpty: {
    legend: { k: "ink", e: ["neutral", 1], f: ["neutral", 0], g: ["neutral", 2] },
    rows: [
      "..kkk....kkk..",
      ".kggek..keeek.",
      "kgeeeekkeeeffk",
      "keeeeeeeeeeefk",
      "keeeeeeeeeeefk",
      "keeeeeeeeeeefk",
      ".keeeeeeeeefk.",
      "..keeeeeeefk..",
      "...keeeeefk...",
      "....keeefk....",
      ".....kefk.....",
      "......kk......",
    ],
  },
  swordBig: {
    legend: { k: "ink", w: ["white", 0], d: ["neutral", 4], c: ["neutral", 3], b: ["neutral", 2], y: ["gold", 3], g: ["gold", 2], h: ["gold", 1], l: ["earth", 2], m: ["earth", 1] },
    rows: [
      "....kk....",
      "...kwdk...",
      "...kwck...",
      "...kdck...",
      "...kdck...",
      "...kdck...",
      "...kdcbk..",
      "...kdcbk..",
      "...kdcbk..",
      "...kdcbk..",
      "...kdcbk..",
      "...kdcbk..",
      "...kdcbk..",
      "...kcbbk..",
      ".kkkkkkkkk",
      "kyyyggggghk",
      ".kkkkllkkk",
      "....klmk..",
      "....klmk..",
      "....klmk..",
      "....kygk..",
      ".....kk...",
    ].map(r => r.padEnd(11, ".")),
  },
  bombBig: {
    legend: { k: "ink", w: ["white", 0], y: ["gold", 3], o: ["red", 3], f: ["earth", 3], d: ["neutral", 3], c: ["neutral", 2], b: ["neutral", 1], a: ["neutral", 0] },
    rows: [
      "..........yo..",
      ".........ky...",
      "........kf....",
      "......kkkk....",
      "....kkdcbkk...",
      "...kdwddcbak..",
      "..kdwdccbbaak.",
      "..kddccbbbaak.",
      "..kdccbbbbaak.",
      "..kccbbbbaaak.",
      "..kcbbbbaaaak.",
      "...kbbbaaaak..",
      "....kkaaakk...",
      "......kkk.....",
    ],
  },
  boomBig: {
    legend: { k: "ink", d: ["earth", 4], c: ["earth", 3], b: ["earth", 2], a: ["earth", 1], r: ["red", 2] },
    rows: [
      ".kkkk.........",
      "kddcck........",
      "kdcbbak.......",
      "kdcbbak.......",
      ".kcbbak.......",
      ".kcrrak.......",
      "..kcbbak......",
      "..kcbbbak.....",
      "...kcbbbakkk..",
      "....kcbbbbbak.",
      ".....kkccbbbak",
      ".......kkcrrak",
      ".........kkkk.",
    ],
  },
  gem: {
    legend: { k: "ink", w: ["white", 0], d: ["water", 4], c: ["water", 3], b: ["water", 2], a: ["water", 1] },
    rows: [
      "...kk...",
      "..kwdk..",
      ".kwddck.",
      "kwddccbk",
      "kdddcbbk",
      "kddccbak",
      ".kdcbak.",
      "..kbak..",
      "...kk...",
    ],
  },
  gemRed: {
    legend: { k: "ink", w: ["white", 0], d: ["red", 3], c: ["red", 2], b: ["red", 1], a: ["red", 0] },
    rows: [
      "...kk...",
      "..kwdk..",
      ".kwddck.",
      "kwddccbk",
      "kdddcbbk",
      "kddccbak",
      ".kdcbak.",
      "..kbak..",
      "...kk...",
    ],
  },
  key: {
    legend: { k: "ink", w: ["white", 0], d: ["gold", 3], c: ["gold", 2], b: ["gold", 1] },
    rows: [
      ".kkkk..",
      "kwddck.",
      "kd..bk.",
      "kd..bk.",
      "kcccbk.",
      ".kcbk..",
      "..kck..",
      "..kcbk.",
      "..kckk.",
      "..kcbbk",
      "..kckk.",
      "..kcbk.",
      "...kk..",
    ],
  },
  bomb: {
    legend: { k: "ink", w: ["white", 0], y: ["gold", 3], o: ["red", 3], f: ["earth", 3], d: ["neutral", 3], c: ["neutral", 2], b: ["neutral", 1], a: ["neutral", 0] },
    rows: [
      "......yo..",
      ".....kf...",
      "...kkkkk..",
      "..kdccbak.",
      ".kdwdcbbak",
      ".kddccbbak",
      ".kdccbbbak",
      ".kccbbbaak",
      "..kbbbaak.",
      "...kkkkk..",
    ],
  },
  sword: {
    legend: { k: "ink", w: ["white", 0], d: ["neutral", 4], c: ["neutral", 3], b: ["neutral", 2], y: ["gold", 3], g: ["gold", 2], h: ["gold", 1], l: ["earth", 2], m: ["earth", 1] },
    rows: [
      "...kk...",
      "..kwdk..",
      "..kwck..",
      "..kdck..",
      "..kdck..",
      "..kdck..",
      "..kdbk..",
      "..kdbk..",
      "..kdbk..",
      "..kdbk..",
      "..kcbk..",
      "kkkcbkkk",
      "kyyggghk",
      "kkklmkkk",
      "..klmk..",
      "..klmk..",
      "..kygk..",
      "...kk...",
    ],
  },
  boomerang: {
    legend: { k: "ink", d: ["earth", 4], c: ["earth", 3], b: ["earth", 2], a: ["earth", 1] },
    rows: [
      ".kkkk.......",
      "kddcck......",
      "kdcbbak.....",
      ".kcbak......",
      "..kcbak.....",
      "...kcbak....",
      "....kcbakk..",
      ".....kcbbak.",
      "......kcbbak",
      ".......kkkk.",
    ],
  },
};

const ICONS = {};
function buildIcons() {
  for (const name in ICON_DEFS) {
    const def = ICON_DEFS[name];
    const lg = {};
    for (const ch in def.legend) {
      const e = def.legend[ch];
      lg[ch] = typeof e === "string" ? (e === "ink" ? inkU32() : pc(e, 0)) : pc(e[0], e[1]);
    }
    ICONS[name] = pixFromRows(def.rows, lg).toCanvas();
  }
}
